[package]
name = "tictactoe_rust"
version = "0.1.0"
authors = ["Daren Liang <darenliang@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
